name: Build and publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - uses: DeterminateSystems/flake-checker-action@v8
      - name: Build
        run: nix build .
      - uses: actions/upload-artifact@v4
        with:
          name: built-slide
          path: ./result
  publish:
    runs-on: ubuntu-latest
    name: Publish
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: built-slide
          path: ./result
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: wattmto-slide
          directory: ./result
          wranglerVersion: '3'
